### ISSUE TITLE
Rust Cargo.toml profiles are ignored unless in root 

### ISSUE THREAD

**Issue by CPerezz** [vacp2p/zerokit#93]
When you compile the lib, you get some warnings from `Cargo` where it correctly says that `profile` sections in `Cargo.toml` that are not the root one are ignored.

And we have a few cases that suffer from this like in `rln-wasm` member:
```toml
[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
```

According to [`Cargo` docs](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides), you can specify in the root workspace a profile for any member like:
```toml
[profile.release.package.WHATEVER_PACKAGE]
opt-level = WHATEVER
```
